config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace :master do
    get '/dashboard', to: 'dashboard#index'
    resources :organizers, except: :edit
    resources :schools, only: [:index, :create, :new, :show]
    resources :members, only: [:index, :show ] do
      resources :managements, only: :destroy
    end
    resources :notices
  end

  namespace :organizer do
    get '/dashboard', to: 'dashboard#index'
    resources :members do
      resources :managements, only: [:new, :edit, :update, :delete]
    end
    resources :notices, only: [:index, :show]
  end

  devise_for :users, controllers: {
      registrations: 'user/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/master.rb
class Master < User
end

app/models/organizer.rb
class Organizer < User
end

app/controllers/master/base_controller.rb
class Master::BaseController < HomeController
  before_action :authenticate_user!, :authorize_user!
end

app/controllers/master/dashboard_controller.rb
class Master::DashboardController < Master::BaseController

  def index
    @schools_organizers = School.find(current_user.school_id).users
    @schools_count = School.count
    @users_count = User.count
    @join_users_count = User.where(status: "join").count
    @members_count = Member.count
    @notices_count = Notice.count
    @managements_count = Management.count
  end

end

app/controllers/master/managements_controller.rb
class Master::ManagementsController < Master::BaseController
end

app/controllers/master/members_controller.rb
class Master::MembersController < Master::BaseController
end

app/controllers/master/notices_controller.rb
class Master::NoticesController < Master::BaseController
  def index

  end
end

app/controllers/master/organizers_controller.rb
class Master::OrganizersController < Master::BaseController
  before_action :set_organizer, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order_by_school.paginate(page: params[:page], per_page: 15)
    @join_users_count = User.where(status: "join").count
  end

  def create
    schools = params[:school_id]

    schools.length.times do |i|
      names = params[:name][i].split
      names.each do |name|
        Organizer.create(name: name, school_id: schools[i])
      end
    end
    redirect_to master_organizers_path
  end

  def new
    # 중앙 운영진(master)가 새로운 학교별 운영진을 등록하는 페이지로 이동
    # 한명씩 등록하는 것이 아닌 원하는 만큼 등록할 수 있도록 dynamic form을 추가 함?
  end

  def show
  end

  def update
    if @organizer.status != "block"
      @organizer.update(status: "block")
      redirect_to master_organizers_path
    else
      if @organizer.email
        @organizer.update(status: "join")
        redirect_to master_organizers_path
      else
        @organizer.update(status: "ready")
        redirect_to master_organizers_path
      end
    end
  end

  def destroy
    @organizer.destroy
    redirect_to master_organizers_path, success: "삭제에 성공했습니다."
  end

  private
  def set_organizer
    @organizer = Organizer.find(params[:id])
  end


end

app/controllers/master/schools_controller.rb
class Master::SchoolsController < Master::BaseController
  def index
    @schools = School.order(:name).all.paginate(page: params[:page], per_page: 15)
  end

  def new
  end

  def create
    count = 0;
    fails = Array.new
    schools = params[:schools].split
    schools.each do |school|
      s = School.new(name: school)
      if s.save
        count = count + 1
      else
        fails.push(school)
      end
    end
    if count == schools.length
      redirect_to master_schools_path, success: "모든 학교를 등록하는데 성공했습니다."
    elsif count == 0
      redirect_to master_schools_path, error: "모든 학교를 등록하지 못했습니다."
    else
      redirect_to master_schools_path, success: "총 #{schools.length - count}의 학교는 등록에 실패했습니다.#{"<br>".html_safe} #{fails.each {|f| f}}"
    end
  end

  def show
    @school = School.find(params[:id])
  end

end

app/controllers/organizer/base_controller.rb
class Organizer::BaseController < HomeController
end

app/controllers/organizer/dashboard_controller.rb
class Organizer::DashboardController < Organizer::BaseController
end

app/controllers/organizer/managements_controller.rb
class Organizer::ManagementsController < Organizer::BaseController
end

app/controllers/organizer/members_controller.rb
class Organizer::MembersController < Organizer::BaseController
end

app/controllers/organizer/notices_controller.rb
class Organizer::NoticesController < Organizer::BaseController
end

app/helpers/master/base_helper.rb
module Master::BaseHelper
end

app/helpers/master/dashboard_helper.rb
module Master::DashboardHelper
end

app/helpers/master/managements_helper.rb
module Master::ManagementsHelper
end

app/helpers/master/members_helper.rb
module Master::MembersHelper
end

app/helpers/master/notices_helper.rb
module Master::NoticesHelper
end

app/helpers/master/organizers_helper.rb
module Master::OrganizersHelper
end

app/views/master/organizers/index.html.erb
<section class="master-organizers">
  <div class="section_header fix shadow">
    <div class="menu_name">
      Organizers
    </div>
    <%= link_to raw("<div class='shadow add'>+</div>"), new_master_organizer_path %>
  </div>

  <article class="index">
    <div class="dashboard">
      <div class="item_group shadow">
        <div class="item">
          등록된 운영진: <span class="number"><%= @users.count %></span>명
        </div>
      </div>
      <div class="item_group shadow">
        <div class="item">
          가입한 운영진: <span class="number"><%= @join_users_count %></span>명
        </div>
      </div>
    </div>
    <div class="table">
      <table class="shadow wrapper">
        <thead>
        <tr>
          <th>이름</th>
          <th>학교</th>
          <th>이메일</th>
          <th>상태</th>
        </tr>
        </thead>
        <tbody>
        <% @users.length.times do |i| %>
            <tr <%= "class=even" if i % 2 == 1 %>>
              <% if @users[i].instance_of? Master %>
                  <td><%= @users[i].name %></td>
                  <td><%= @users[i].school.name %></td>
              <% else %>
                  <td><%= link_to "#{@users[i].name}", master_organizer_path(@users[i]) %></td>
                  <td><%= link_to "#{@users[i].school.name}", master_school_path(@users[i].school) %></td>
              <% end %>
              <td><%= @users[i].email %></td>
              <td><%= @users[i].status %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <%= render 'partial/pagenation' %>


  </article>
</section>

app/views/master/organizers/new.html.erb
<section>
  <div class="section_header fix shadow">
    <div class="menu_name">
      Organizers - New
    </div>
    <%= link_to raw("<div class='shadow back'>되돌아가기</div>"), master_organizers_path %>
  </div>

  <article>
    <%= form_tag master_organizers_path, method: :post, id: "new_organizer" %>
    <div class="inputcontainer">
      <div>
        <%= select_tag "school_id[]", options_from_collection_for_select(schools, "id", "name") %>

        <%= text_area_tag "name[]", nil, placeholder: '학교를 선택한 후 이름을 엔터로 구분하여 입력하세요' %>
      </div>
    </div>
    <div class="buttonarea">
      <button type="button" id="addNewSchool">학교 추가</button>
      <%= submit_tag '등록' %>
    </div>
  </article>
</section>

<div style="display: none;" id="new_input_form">
  <div>
    <%= select_tag "school_id[]", options_from_collection_for_select(schools, "id", "name") %>

    <%= text_area_tag "name[]", nil, placeholder: '학교를 선택한 후 이름을 엔터로 구분하여 입력하세요' %>
  </div>
</div>
<!--이 블럭 때문에 데이터가 배열로 하나 더 들어가는 문제가 있음 size - 1 로 계산해야함 -->
<script type="text/javascript" charset="utf-8">
    $(function () {
        $("#addNewSchool").click(function () {
            $(".inputcontainer").append($("#new_input_form").html())
        });
    });
</script>

app/views/master/organizers/show.html.erb
<section class="master-organizers">
  <div class="section_header fix shadow">
    <div class="menu_name">
      Organizers - Show
    </div>
    <%= link_to raw("<div class='shadow back'>되돌아가기</div>"), master_organizers_path %>
  </div>

  <article class="show">
    <div class="organizer-info shadow">
      <div class="name"><%= @organizer.name %></div>
      <div class="basic">
        <%= @organizer.school.name %> <br>
        <%= @organizer.email %> <br>
        상태 : <%= @organizer.status %>
      </div>
      <div class="date">
        <div>등록일<br><%= @organizer.created_at.to_formatted_s(:short) %></div>
        <div>상태변경일<br><%= @organizer.updated_at.to_formatted_s(:short) %></div>
      </div>
      <div class="btn-group">
        <% if @organizer.status == "block" %>
            <%= link_to '정상처리', master_organizer_path(@organizer), method: :patch %>
        <% else %>
            <%= link_to '블럭처리', master_organizer_path(@organizer), method: :patch %>
        <% end %>
        <%= link_to '삭제', master_organizer_path(@organizer), method: :delete, data: {confirm: "'#{@organizer.school.name}의 #{@organizer.name}'를(을) 삭제시키겠습니까? (삭제된 데이터는 복원되지 않습니다.)"} %>
      </div>
    </div>
    <div class="management shadow">
      관리부1 <br>
      관리부2
    </div>
  </article>
</section>