config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace :master do
    get '/dashboard', to: 'dashboard#index'
    resources :organizers, except: :edit
    resources :schools, only: [:index, :create, :new, :show]
    resources :members, only: [:index, :show ] do
      resources :managements, only: :destroy
    end
    resources :notices
  end

  namespace :organizer do
    get '/dashboard', to: 'dashboard#index'
    resources :members do
      resources :managements, only: [:new, :edit, :update, :delete]
    end
    resources :notices, only: [:index, :show]
  end

  devise_for :users, controllers: {
      registrations: 'user/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/management.rb
class Management < ApplicationRecord
  belongs_to :member, counter_cache: true
  belongs_to :user
end

app/models/master.rb
class Master < User
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :school, counter_cache: true
  has_many :managements
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/models/organizer.rb
class Organizer < User
end

app/models/school.rb
class School < ApplicationRecord
  has_many :users
  has_many :members
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  belongs_to :school, foreign_key: :school_id, counter_cache: true
  has_many :managements

  validates_uniqueness_of       :email,    :case_sensitive => false,          :allow_blank => true, :if => :email_changed?
  validates_format_of           :email,    :with  => Devise.email_regexp,     :allow_blank => true, :if => :email_changed?
  validates_confirmation_of     :password, :on=>:create
  validates_length_of           :password, :within => Devise.password_length, :allow_blank => true

  def self.order_by_school
    joins(:school).merge(School.order(:name))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :error, :warning, :success

  #protect_from_forgery with: :exception

  private
  def authorize_user!
    unless current_user.instance_of? Master
      redirect_to root_path, warning: "접근을 하려면 권한이 필요합니다."
    end
  end

  def authenticate_user!
    unless user_signed_in?
      redirect_to new_user_session_path, warning: "로그인이 필요합니다."
      # else
      #   if current_user.status == ready
      #
      #   end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless user_signed_in?
      render 'devise/sessions/new'
    else
      if current_user.status == "block"
        render partial: 'partial/block'
      else
        if current_user.instance_of? Master
          redirect_to master_dashboard_path
        else
          redirect_to organizer_dashboard_path
        end
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    User
  end

  def schools
    School.order(:name).all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/master/base_helper.rb
module Master::BaseHelper
end

app/helpers/master/dashboard_helper.rb
module Master::DashboardHelper
end

app/helpers/master/members_helper.rb
module Master::MembersHelper
end

app/helpers/master/notices_helper.rb
module Master::NoticesHelper
end

app/helpers/master/organizers_helper.rb
module Master::OrganizersHelper
end

app/helpers/master/schools_helper.rb
module Master::SchoolsHelper
end

app/helpers/organizer/base_helper.rb
module Organizer::BaseHelper
end

app/helpers/organizer/members_helper.rb
module Organizer::MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LikeLionMemberManagementProto3</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


</head>

<body>
<%= render 'partial/flash_messages' %>
<% if user_signed_in? %>
    <%= render 'partial/nav' %>
<% end %>


<%= yield %>

</body>
</html>

app/views/partial/_block.html.erb
해당 아이디는 블럭 처리 되었습니다.
블럭처리된 아이디는 사용하실 수 없습니다.

<%= link_to '로그아웃', destroy_user_session_path, method: :delete, data: { confirm: "로그아웃 하시겠습니까?" } %>

app/views/partial/_flash_messages.html.erb
<div class="flash">
  <% flash.each do |type, msg| %>
      <div class="<%= type %>">
        <%= msg %>
      </div>
  <% end %>
</div>

app/views/partial/_nav.html.erb
<div class="fix">
  <header class="shadow">
    <%= link_to '멋쟁이 사자처럼', root_path, id: "logo" %>
    <div class="profile">
      <div class="wrapper_wide">
        <div class="avatar"></div>
        <div class="info">
          <%= current_user.name %><br>
          <span class="school"><%= current_user.school.name %></span></div>
      </div>
      <div class="menu">
        <%= link_to '로그아웃', destroy_user_session_path, method: :delete, data: {confirm: "로그아웃 하시겠습니까?"} %>
      </div>
    </div>
    <nav>
      <% if current_user.instance_of? Master %>
          <% if controller_name == "dashboard" %>
              <%= link_to raw("<div class='menu_item menu_clicked'>#{image_tag 'dashboard.png'}<div>대시보드</div></div>"), master_dashboard_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'notice.png'}<div>공지사항</div></div>"), master_notices_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'school.png'}<div>학교관리</div></div>"), master_schools_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'people.png'}<div>운영진관리</div></div>"), master_organizers_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'people.png'}<div>참여생관리</div></div>"), master_members_path %>
          <% elsif controller_name == "members" %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'dashboard.png'}<div>대시보드</div></div>"), master_dashboard_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'notice.png'}<div>공지사항</div></div>"), master_notices_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'school.png'}<div>학교관리</div></div>"), master_schools_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'people.png'}<div>운영진관리</div></div>"), master_organizers_path %>
              <%= link_to raw("<div class='menu_item menu_clicked'>#{image_tag 'people.png'}<div>참여생관리</div></div>"), master_members_path %>
          <% elsif controller_name == "notices" %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'dashboard.png'}<div>대시보드</div></div>"), master_dashboard_path %>
              <%= link_to raw("<div class='menu_item menu_clicked'>#{image_tag 'notice.png'}<div>공지사항</div></div>"), master_notices_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'school.png'}<div>학교관리</div></div>"), master_schools_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'people.png'}<div>운영진관리</div></div>"), master_organizers_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'people.png'}<div>참여생관리</div></div>"), master_members_path %>
          <% elsif controller_name == "organizers" %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'dashboard.png'}<div>대시보드</div></div>"), master_dashboard_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'notice.png'}<div>공지사항</div></div>"), master_notices_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'school.png'}<div>학교관리</div></div>"), master_schools_path %>
              <%= link_to raw("<div class='menu_item menu_clicked'>#{image_tag 'people.png'}<div>운영진관리</div></div>"), master_organizers_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'people.png'}<div>참여생관리</div></div>"), master_members_path %>
          <% elsif controller_name == "schools" %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'dashboard.png'}<div>대시보드</div></div>"), master_dashboard_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'notice.png'}<div>공지사항</div></div>"), master_notices_path %>
              <%= link_to raw("<div class='menu_item menu_clicked'>#{image_tag 'school.png'}<div>학교관리</div></div>"), master_schools_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'people.png'}<div>운영진관리</div></div>"), master_organizers_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'people.png'}<div>참여생관리</div></div>"), master_members_path %>
          <% end %>
      <% else %>
          <% if controller_name == "dashboard" %>
              <%= link_to raw("<div class='menu_item menu_clicked'>#{image_tag 'dashboard.png'}<div>대시보드</div></div>"), master_dashboard_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'notice.png'}<div>공지사항</div></div>"), master_notices_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'people.png'}<div>운영진관리</div></div>"), master_organizers_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'people.png'}<div>관리부</div></div>"), master_members_path %>
          <% elsif controller_name == "members" %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'dashboard.png'}<div>대시보드</div></div>"), master_dashboard_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'notice.png'}<div>공지사항</div></div>"), master_notices_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'people.png'}<div>운영진관리</div></div>"), master_organizers_path %>
              <%= link_to raw("<div class='menu_item menu_clicked'>#{image_tag 'people.png'}<div>관리부</div></div>"), master_members_path %>
          <% elsif controller_name == "notices" %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'dashboard.png'}<div>대시보드</div></div>"), master_dashboard_path %>
              <%= link_to raw("<div class='menu_item menu_clicked'>#{image_tag 'notice.png'}<div>공지사항</div></div>"), master_notices_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'people.png'}<div>운영진관리</div></div>"), master_organizers_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'people.png'}<div>관리부</div></div>"), master_members_path %>
          <% elsif controller_name == "managements" %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'dashboard.png'}<div>대시보드</div></div>"), master_dashboard_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'notice.png'}<div>공지사항</div></div>"), master_notices_path %>
              <%= link_to raw("<div class='menu_item'>#{image_tag 'people.png'}<div>운영진관리</div></div>"), master_organizers_path %>
              <%= link_to raw("<div class='menu_item managements'>#{image_tag 'people.png'}<div>관리부</div></div>"), master_members_path %>
          <% end %>
      <% end %>
    </nav>
  </header>
</div>

app/views/partial/_pagenation.html.erb
<%= will_paginate @users, previous_label: "이전", next_label: "다음", inner_window: 3, outer_window: 0 %>