config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace :master do
    get '/dashboard', to: 'dashboard#index'
    resources :organizers, except: :edit
    resources :schools, only: [:index, :create, :new, :show]
    resources :members, only: [:index, :show ] do
      resources :managements, only: :destroy
    end
    resources :notices
  end

  namespace :organizer do
    get '/dashboard', to: 'dashboard#index'
    resources :members do
      resources :managements, only: [:new, :edit, :update, :delete]
    end
    resources :notices, only: [:index, :show]
  end

  devise_for :users, controllers: {
      registrations: 'user/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/master.rb
class Master < User
end

app/models/school.rb
class School < ApplicationRecord
  has_many :users
  has_many :members
end

app/controllers/master/base_controller.rb
class Master::BaseController < HomeController
  before_action :authenticate_user!, :authorize_user!
end

app/controllers/master/dashboard_controller.rb
class Master::DashboardController < Master::BaseController

  def index
    @schools_organizers = School.find(current_user.school_id).users
    @schools_count = School.count
    @users_count = User.count
    @join_users_count = User.where(status: "join").count
    @members_count = Member.count
    @notices_count = Notice.count
    @managements_count = Management.count
  end

end

app/controllers/master/managements_controller.rb
class Master::ManagementsController < Master::BaseController
end

app/controllers/master/members_controller.rb
class Master::MembersController < Master::BaseController
end

app/controllers/master/notices_controller.rb
class Master::NoticesController < Master::BaseController
  def index

  end
end

app/controllers/master/organizers_controller.rb
class Master::OrganizersController < Master::BaseController
  before_action :set_organizer, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order_by_school.paginate(page: params[:page], per_page: 15)
    @join_users_count = User.where(status: "join").count
  end

  def create
    schools = params[:school_id]

    schools.length.times do |i|
      names = params[:name][i].split
      names.each do |name|
        Organizer.create(name: name, school_id: schools[i])
      end
    end
    redirect_to master_organizers_path
  end

  def new
    # 중앙 운영진(master)가 새로운 학교별 운영진을 등록하는 페이지로 이동
    # 한명씩 등록하는 것이 아닌 원하는 만큼 등록할 수 있도록 dynamic form을 추가 함?
  end

  def show
  end

  def update
    if @organizer.status != "block"
      @organizer.update(status: "block")
      redirect_to master_organizers_path
    else
      if @organizer.email
        @organizer.update(status: "join")
        redirect_to master_organizers_path
      else
        @organizer.update(status: "ready")
        redirect_to master_organizers_path
      end
    end
  end

  def destroy
    @organizer.destroy
    redirect_to master_organizers_path, success: "삭제에 성공했습니다."
  end

  private
  def set_organizer
    @organizer = Organizer.find(params[:id])
  end


end

app/controllers/master/schools_controller.rb
class Master::SchoolsController < Master::BaseController
  def index
    @schools = School.order(:name).all.paginate(page: params[:page], per_page: 15)
  end

  def new
  end

  def create
    count = 0;
    fails = Array.new
    schools = params[:schools].split
    schools.each do |school|
      s = School.new(name: school)
      if s.save
        count = count + 1
      else
        fails.push(school)
      end
    end
    if count == schools.length
      redirect_to master_schools_path, success: "모든 학교를 등록하는데 성공했습니다."
    elsif count == 0
      redirect_to master_schools_path, error: "모든 학교를 등록하지 못했습니다."
    else
      redirect_to master_schools_path, success: "총 #{schools.length - count}의 학교는 등록에 실패했습니다.#{"<br>".html_safe} #{fails.each {|f| f}}"
    end
  end

  def show
    @school = School.find(params[:id])
  end

end

app/helpers/master/base_helper.rb
module Master::BaseHelper
end

app/helpers/master/dashboard_helper.rb
module Master::DashboardHelper
end

app/helpers/master/managements_helper.rb
module Master::ManagementsHelper
end

app/helpers/master/members_helper.rb
module Master::MembersHelper
end

app/helpers/master/notices_helper.rb
module Master::NoticesHelper
end

app/helpers/master/organizers_helper.rb
module Master::OrganizersHelper
end

app/helpers/master/schools_helper.rb
module Master::SchoolsHelper
end

app/views/master/schools/index.html.erb
<section class="master-schools">
  <div class="section_header fix shadow">
    <div class="menu_name">
      Schools
    </div>
    <%= link_to raw("<div class='shadow add'>+</div>"), new_master_school_path %>
  </div>

  <article class="index">
    <div class="count shadow">
      총 학교 : <span><%= @schools.count %></span>개
    </div>

    <table class="shadow">
      <thead>
      <tr>
        <th>학교</th>
        <th>운영진</th>
        <th>참여생</th>
      </tr>
      </thead>
      <tbody>
      <% @schools.each_with_index do |school, index| %>
          <% if index  % 2 != 0 %>
              <tr class="even">
          <% else %>
              <tr>
          <% end %>

          <td><%= link_to raw("#{school.name}"), master_school_path(school) %> </td>
          <td><%= school.users.size %>명</td>
          <td><%= school.members.size %>명</td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <%= render 'partial/pagenation' %>
  </article>
</section>

app/views/master/schools/new.html.erb
<section class="master-schools">
  <div class="section_header fix shadow">
    <div class="menu_name">
      Schools - New
    </div>
    <%= link_to raw("<div class='shadow back'>되돌아가기</div>"), master_schools_path %>
  </div>

  <article class="new">
    <%= form_tag master_schools_path, method: :post, id: 'new-schools' %>

    <%= text_area_tag "schools", nil, placeholder: '새로 추가할 학교를 입력하세요. 구분은 엔터로 합니다.' %>

    <%= submit_tag '추가' %>
  </article>
</section>

app/views/master/schools/show.html.erb
<section class="master-schools">
  <div class="section_header fix shadow">
    <div class="menu_name">
      Schools - Show
    </div>
    <%= link_to raw("<div class='shadow back'>되돌아가기</div>"), master_schools_path %>
  </div>

  <article class="show">
    <div class="school_info">
      <div class="name"><%= @school.name %></div>
      <div class="countings">총 운영진 : <span class="number"><%= @school.users.size %></span> 총 참여생 :
        <span class="number"><%= @school.members.size %></span></div>
    </div>
    <div class="content">
      <div class="organizers"></div>
      <div class="members"></div>
    </div>
  </article>
</section>